local function equal(actual, expected)
    assert(actual == expected, tostring(actual) .. " ~= " .. tostring(expected))
end

local P = DP.Parser
local english = P.Compile("%s has defeated %s in a duel.")
local w, l = P.Match(english, "Mâge has defeated Bob-Realm in a duel.")
equal(w, "Mâge"); equal(l, "Bob-Realm")
equal(P.Match(english, "prefix Mâge has defeated Bob-Realm in a duel."), nil)
equal(P.Match(english, "Mâge has defeated Bob-Realm in a duel!"), nil)
local reordered = P.Compile("[%2$s] lost to (%1$s)! 100%%")
w, l = P.Match(reordered, "[Bob] lost to (Alice)! 100%")
equal(w, "Alice"); equal(l, "Bob")
equal(P.Compile("%s beat %d"), nil)
equal(P.Compile("%1$s beat %1$s"), nil)
equal(P.Compile("%3$s beat %1$s"), nil)
equal(P.Compile(nil), nil)
equal(P.SameName("Alice-Realm", "Alice"), true)
equal(P.SameName("Alice-Realm", "Alice-Other"), false)
equal(P.SameName("Alice", "Alicia"), false)

local records = {}
local t = DP.Tracker.New("Alice-Realm", function(r) records[#records + 1] = r end)
equal(t:Result("Bob", "Charlie", "knockout", 1), false)
equal(#records, 0)
t:Request("Bob", "incoming", false, 2)
equal(t:Result("Alice", "Bob", "knockout", 10), true)
equal(records[1].status, "matched-request-history-only")
equal(records[1].ratingEligible, false)
equal(records[1].durationQuality, "unknown")
equal(t:Finished(10.1), nil)
equal(t:Result("Alice", "Bob", "knockout", 10.2), false)
equal(#records, 1)
local id = t:Request("Bob", "incoming", false, 11)
equal(t:Request("Bob", "incoming", false, 11.1), id)
equal(t:Finished(11.5), id)
equal(t:Result("Bob", "Alice", "retreat", 12), true)
t:Expire(id, 15)
equal(#records, 2)
equal(records[2].won, false)
equal(records[2].outcome, "retreat")

local oldId = t:Request("Bob", "incoming", false, 20)
t:Finished(21)
local newId = t:Request("Charlie", "incoming", false, 22)
t:Expire(oldId, 24)
equal(t.session.id, newId)
t:Result("Alice", "Bob", "knockout", 25)
equal(records[#records].status, "identity-conflict")

t:Request("Bob", "incoming", true, 30)
t:Result("Alice", "Bob", "knockout", 35)
equal(records[#records].status, "excluded-duel-type")
t:Result("Alice", "Charlie", "knockout", 40)
equal(records[#records].status, "recovered-history-only")
id = t:Request("Bob", "incoming", false, 45)
t:Finished(46)
t:Expire(id, 49)
equal(records[#records].kind, "activity")
equal(records[#records].status, "no-result-unresolved")
equal(t.session, nil)

-- A quick rematch with its own request is not discarded by the duplicate guard.
t:Request("Bob", "incoming", false, 50)
t:Result("Alice", "Bob", "knockout", 51)
t:Request("Bob", "incoming", false, 52)
equal(t:Result("Alice", "Bob", "knockout", 53), true)
print("PASS: parser and tracker scenarios")

equal(P.Countdown("Duel starting: %d", "Duel starting: 3"), 3)
equal(P.Countdown("Start [%1$d]", "Start [2]"), 2)
equal(P.Countdown("Duel starting: %d", "Duel starting: 0"), nil)
equal(P.Countdown("Duel starting: %d", "prefix Duel starting: 3"), nil)
equal(P.Countdown(nil, "Duel starting: 3"), nil)
local captures = {}
local live = DP.Tracker.New("Zurk-Kurinnaxx", function(r) captures[#captures + 1] = r end)
-- Replay the supplied 1.15.9 trace with its actual monotonic timestamps.
live:Request("Trînket-Whitemane", "outgoing-intent", false, 155825.095)
live:Close("cancelled", 155832.287)
equal(live:Finished(155832.287), nil)
live:Request("Santlea-Whitemane", "outgoing-intent", false, 155840.005)
live:Close("cancelled", 155844.271)
live:Request("Vitoarcanjo-Whitemane", "outgoing-intent", false, 155894.024)
live:Countdown(3, 155897.600)
live:Countdown(2, 155898.600)
live:Countdown(1, 155899.600)
equal(live.session.acceptedAt, 155897.600)
live:Finished(155903.608)
live:Result("Vitoarcanjo-Whitemane", "Zurk", "knockout", 155903.608)
equal(#captures, 3)
equal(captures[1].status, "cancelled")
equal(captures[2].status, "cancelled")
equal(captures[3].won, false)
assert(math.abs(captures[3].duration - 3.008) < 0.0001)
equal(captures[3].durationQuality, "estimated")
equal(live:Countdown(3, 155910), false)
local sid = live:Request("Bob", "incoming", false, 155920)
live:Countdown(3, 155921)
equal(live:Countdown(3, 155922), false)
live:Result("Zurk", "Bob", "knockout", 155922)
equal(captures[#captures].durationQuality, "unknown")
print("PASS: supplied Classic Era trace replay and countdown guards")
